name: build

on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix run nixpkgs#hello
