name: build

on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run "echo OK"
